### ISSUE TITLE
Edit/Update Functionality -> Backend

### ISSUE THREAD

**Issue by agentkalu** [GPropersi/urls4irl#17]
To edit or update names of UTub

**Comment by rehankalu** [comment]
Can also be extended to accept changes to URLs, or tag text

**Comment by GPropersi** [comment]
- UTub Names
- UTub Descriptions
- URLs
- URL Descriptions
- Tags

Anything else?

**Comment by rehankalu** [comment]
POST to /url/edit/[UTubID]/[URLID] returns success but on page refresh shows it did not save to db
