### ISSUE TITLE
Add Tag to UTub - no URL

### ISSUE THREAD

**Issue by rehankalu** [GPropersi/urls4irl#40]
Progressive suggestion dropdown list using tags from the current user's other UTubs. Analogous to the functionality of Add Tag to UTub w/ URL which pulls suggestions from other tags in the UTub. Requires tag decks from other UTubs sent from the backend somehow...

**Comment by GPropersi** [comment]
Duplicate of issue #20 ?

**Comment by rehankalu** [comment]
Duplicated of #20
